### ISSUE TITLE
[ETC] 이미지 업로드 아이콘 스타일 조정 필요

### ISSUE THREAD

**Issue by SEMINSEMINSEMIN** [nailedReact/react-app#334]
상품 등록시
<img width="412" alt="스크린샷 2022-12-30 오후 6 32 38" src="https://user-images.githubusercontent.com/104843477/210055402-440c9c29-c766-4ef1-9538-db91df70a792.png">

#329 해결하다가 스타일 건들면서 문제가 생김

**Comment by sasha1107** [comment]
세민님 이부분 제가 수정했습니다!!
해당 커밋 → [```6f82ffb```](https://github.com/nailedReact/react-app/commit/6f82ffbdc4f7a756beb9ea95c0a4d6e493d39904)

**Comment by SEMINSEMINSEMIN** [comment]
> 세민님 이부분 제가 수정했습니다!!
> 
> 해당 커밋 → [```6f82ffb```](https://github.com/nailedReact/react-app/commit/6f82ffbdc4f7a756beb9ea95c0a4d6e493d39904)

감사합니다!
