### ISSUE TITLE
[PROFILE] 다른 사람 페이지 후 내 프로필 페이지 들어가면 포스트리스트 재렌더링 x

### ISSUE THREAD

**Issue by SEMINSEMINSEMIN** [nailedReact/react-app#348]
https://user-images.githubusercontent.com/104843477/210171152-e520005a-d747-40f2-9b7d-3a3396f17fc5.MOV

**Comment by sasha1107** [comment]
헉 저 이거 해결하려다 실패했는데,,,ㅋㅋㅋ감사합니다 세민님!!
